import { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { authenticate } from '../middleware/auth';

const uuidParam = z.string().uuid();
function parseId(id: string, reply: FastifyReply): string | null {
  const r = uuidParam.safeParse(id);
  if (!r.success) {
    reply.status(400).send({ error: 'VALIDATION_ERROR', message: 'Invalid ID format' });
    return null;
  }
  return r.data;
}

const createSchema = z.object({
  name:                z.string().min(1).max(255),
  description:         z.string().max(2000).optional(),
  category:            z.string().max(100).optional(),
  billing_cycle:       z.enum(['weekly', 'monthly', 'quarterly', 'yearly']),
  price:               z.number().nonnegative(),
  currency:            z.string().max(10).default('USD'),
  status:              z.enum(['active', 'trial', 'paused', 'cancelled', 'expired', 'pending']).default('active'),
  start_date:          z.string().datetime(),
  next_billing_date:   z.string().datetime().optional(),
  trial_end_date:      z.string().datetime().optional(),
  reminder_days_before: z.number().int().min(0).max(30).default(3),
  notes:               z.string().max(5000).optional(),
  color:               z.string().max(20).optional(),
  icon:                z.string().max(10).optional(),
  website:             z.string().max(500).optional(),
});

const updateSchema = createSchema.partial();

const listQuerySchema = z.object({
  page:     z.coerce.number().int().min(1).default(1),
  limit:    z.coerce.number().int().min(1).max(100).default(50),
  status:   z.enum(['active', 'trial', 'paused', 'cancelled', 'expired', 'pending']).optional(),
  category: z.string().optional(),
  search:   z.string().optional(),
});

// ─── Helper: compute price normalized to monthly & yearly ────────────────────
function normalizePrice(price: number, cycle: string) {
  switch (cycle) {
    case 'weekly':    return { monthly: price * 4.33, yearly: price * 52 };
    case 'monthly':   return { monthly: price,        yearly: price * 12 };
    case 'quarterly': return { monthly: price / 3,    yearly: price * 4 };
    case 'yearly':    return { monthly: price / 12,   yearly: price };
    default:          return { monthly: price,        yearly: price * 12 };
  }
}

// ─── Helper: schedule/update linked reminder ─────────────────────────────────
async function upsertLinkedReminder(
  server: FastifyInstance,
  userId: string,
  sub: { id: string; name: string; nextBillingDate: Date | null; reminderDaysBefore: number; reminderId: string | null },
): Promise<string | null> {
  if (!sub.nextBillingDate) return sub.reminderId;

  const fireAt = new Date(sub.nextBillingDate);
  fireAt.setDate(fireAt.getDate() - sub.reminderDaysBefore);
  fireAt.setHours(9, 0, 0, 0); // 9am on reminder day

  if (fireAt < new Date()) return sub.reminderId; // already past — skip

  const title = `💳 ${sub.name} — subscription due`;

  if (sub.reminderId) {
    // Update existing reminder
    try {
      await server.prisma.reminder.update({
        where: { id: sub.reminderId },
        data: { title, fireAt },
      });
    } catch {
      // reminder was deleted — create new one below
    } finally {
      return sub.reminderId;
    }
  }

  // Create a new reminder
  const reminder = await server.prisma.reminder.create({
    data: {
      userId,
      type:     'task',
      title,
      fireAt,
      status:   'pending',
      priority: 'medium',
      notes:    `Subscription reminder — auto-generated by GoodLifeTask`,
    },
  });

  return reminder.id;
}

export async function userSubscriptionsRoutes(server: FastifyInstance) {

  // ── GET /v1/user-subscriptions ───────────────────────────────────────────
  server.get('/', { preHandler: [authenticate] }, async (req: FastifyRequest, reply: FastifyReply) => {
    const userId = req.user.sub;
    const q = listQuerySchema.parse(req.query);
    const skip = (q.page - 1) * q.limit;

    const where: any = { userId, deletedAt: null };
    if (q.status)   where.status   = q.status;
    if (q.category) where.category = { contains: q.category, mode: 'insensitive' };
    if (q.search)   where.name     = { contains: q.search,   mode: 'insensitive' };

    const [items, total] = await Promise.all([
      server.prisma.userSubscription.findMany({
        where,
        skip,
        take: q.limit,
        orderBy: [{ status: 'asc' }, { nextBillingDate: 'asc' }],
      }),
      server.prisma.userSubscription.count({ where }),
    ]);

    // Aggregate stats across ALL active/trial subscriptions (no pagination filter)
    const allActive = await server.prisma.userSubscription.findMany({
      where: { userId, deletedAt: null, status: { in: ['active', 'trial'] } },
      select: { price: true, billingCycle: true },
    });

    let totalMonthly = 0;
    let totalYearly  = 0;
    for (const s of allActive) {
      const n = normalizePrice(Number(s.price), s.billingCycle);
      totalMonthly += n.monthly;
      totalYearly  += n.yearly;
    }

    return reply.send({
      success: true,
      data: items,
      total,
      page: q.page,
      limit: q.limit,
      stats: {
        totalMonthly: Math.round(totalMonthly * 100) / 100,
        totalYearly:  Math.round(totalYearly  * 100) / 100,
        activeCount:  allActive.length,
      },
    });
  });

  // ── GET /v1/user-subscriptions/stats ─────────────────────────────────────
  server.get('/stats', { preHandler: [authenticate] }, async (req: FastifyRequest, reply: FastifyReply) => {
    const userId = req.user.sub;

    const all = await server.prisma.userSubscription.findMany({
      where: { userId, deletedAt: null },
      select: { price: true, billingCycle: true, status: true, nextBillingDate: true },
    });

    let totalMonthly = 0;
    let totalYearly  = 0;
    const byStatus: Record<string, number> = {};
    const upcoming: typeof all = [];
    const now = new Date();
    const in7Days = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

    for (const s of all) {
      byStatus[s.status] = (byStatus[s.status] ?? 0) + 1;
      if (s.status === 'active' || s.status === 'trial') {
        const n = normalizePrice(Number(s.price), s.billingCycle);
        totalMonthly += n.monthly;
        totalYearly  += n.yearly;
      }
      if (s.nextBillingDate && s.nextBillingDate >= now && s.nextBillingDate <= in7Days) {
        upcoming.push(s);
      }
    }

    return reply.send({
      success: true,
      data: {
        totalMonthly: Math.round(totalMonthly * 100) / 100,
        totalYearly:  Math.round(totalYearly  * 100) / 100,
        total:        all.length,
        byStatus,
        upcomingInWeek: upcoming.length,
      },
    });
  });

  // ── GET /v1/user-subscriptions/:id ───────────────────────────────────────
  server.get('/:id', { preHandler: [authenticate] }, async (req: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const id = parseId(req.params.id, reply);
    if (!id) return;

    const sub = await server.prisma.userSubscription.findFirst({
      where: { id, userId: req.user.sub, deletedAt: null },
    });
    if (!sub) return reply.status(404).send({ error: 'NOT_FOUND', message: 'Subscription not found' });

    return reply.send({ success: true, data: sub });
  });

  // ── POST /v1/user-subscriptions ──────────────────────────────────────────
  server.post('/', { preHandler: [authenticate] }, async (req: FastifyRequest, reply: FastifyReply) => {
    const userId = req.user.sub;
    const body = createSchema.parse(req.body);

    const sub = await server.prisma.userSubscription.create({
      data: {
        userId,
        name:                body.name,
        description:         body.description,
        category:            body.category,
        billingCycle:        body.billing_cycle,
        price:               body.price,
        currency:            body.currency,
        status:              body.status,
        startDate:           new Date(body.start_date),
        nextBillingDate:     body.next_billing_date ? new Date(body.next_billing_date) : null,
        trialEndDate:        body.trial_end_date    ? new Date(body.trial_end_date)    : null,
        reminderDaysBefore:  body.reminder_days_before,
        notes:               body.notes,
        color:               body.color,
        icon:                body.icon,
        website:             body.website,
      },
    });

    // Auto-create linked reminder
    const reminderId = await upsertLinkedReminder(server, userId, {
      id:                 sub.id,
      name:               sub.name,
      nextBillingDate:    sub.nextBillingDate,
      reminderDaysBefore: sub.reminderDaysBefore,
      reminderId:         null,
    });

    const updated = reminderId
      ? await server.prisma.userSubscription.update({
          where: { id: sub.id },
          data: { reminderId },
        })
      : sub;

    return reply.status(201).send({ success: true, data: updated });
  });

  // ── PATCH /v1/user-subscriptions/:id ─────────────────────────────────────
  server.patch('/:id', { preHandler: [authenticate] }, async (req: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const userId = req.user.sub;
    const id = parseId(req.params.id, reply);
    if (!id) return;

    const existing = await server.prisma.userSubscription.findFirst({
      where: { id, userId, deletedAt: null },
    });
    if (!existing) return reply.status(404).send({ error: 'NOT_FOUND', message: 'Subscription not found' });

    const body = updateSchema.parse(req.body);

    const sub = await server.prisma.userSubscription.update({
      where: { id },
      data: {
        ...(body.name               !== undefined && { name:               body.name }),
        ...(body.description        !== undefined && { description:        body.description }),
        ...(body.category           !== undefined && { category:           body.category }),
        ...(body.billing_cycle      !== undefined && { billingCycle:       body.billing_cycle }),
        ...(body.price              !== undefined && { price:              body.price }),
        ...(body.currency           !== undefined && { currency:           body.currency }),
        ...(body.status             !== undefined && { status:             body.status }),
        ...(body.start_date         !== undefined && { startDate:          new Date(body.start_date) }),
        ...(body.next_billing_date  !== undefined && { nextBillingDate:    new Date(body.next_billing_date) }),
        ...(body.trial_end_date     !== undefined && { trialEndDate:       new Date(body.trial_end_date) }),
        ...(body.reminder_days_before !== undefined && { reminderDaysBefore: body.reminder_days_before }),
        ...(body.notes              !== undefined && { notes:              body.notes }),
        ...(body.color              !== undefined && { color:              body.color }),
        ...(body.icon               !== undefined && { icon:               body.icon }),
        ...(body.website            !== undefined && { website:            body.website }),
      },
    });

    // Re-sync reminder if billing date or days changed
    if (body.next_billing_date !== undefined || body.reminder_days_before !== undefined) {
      const reminderId = await upsertLinkedReminder(server, userId, {
        id:                 sub.id,
        name:               sub.name,
        nextBillingDate:    sub.nextBillingDate,
        reminderDaysBefore: sub.reminderDaysBefore,
        reminderId:         sub.reminderId,
      });
      if (reminderId !== sub.reminderId) {
        await server.prisma.userSubscription.update({ where: { id }, data: { reminderId } });
        return reply.send({ success: true, data: { ...sub, reminderId } });
      }
    }

    return reply.send({ success: true, data: sub });
  });

  // ── POST /v1/user-subscriptions/:id/cancel ───────────────────────────────
  server.post('/:id/cancel', { preHandler: [authenticate] }, async (req: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const id = parseId(req.params.id, reply);
    if (!id) return;

    const existing = await server.prisma.userSubscription.findFirst({
      where: { id, userId: req.user.sub, deletedAt: null },
    });
    if (!existing) return reply.status(404).send({ error: 'NOT_FOUND', message: 'Subscription not found' });

    const sub = await server.prisma.userSubscription.update({
      where: { id },
      data: { status: 'cancelled', cancelledAt: new Date() },
    });

    // Cancel linked reminder
    if (existing.reminderId) {
      await server.prisma.reminder.updateMany({
        where: { id: existing.reminderId, status: 'pending' },
        data:  { status: 'deleted', deletedAt: new Date() },
      });
    }

    return reply.send({ success: true, data: sub });
  });

  // ── POST /v1/user-subscriptions/:id/pause ────────────────────────────────
  server.post('/:id/pause', { preHandler: [authenticate] }, async (req: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const id = parseId(req.params.id, reply);
    if (!id) return;

    const existing = await server.prisma.userSubscription.findFirst({
      where: { id, userId: req.user.sub, deletedAt: null },
    });
    if (!existing) return reply.status(404).send({ error: 'NOT_FOUND', message: 'Subscription not found' });

    const sub = await server.prisma.userSubscription.update({
      where: { id },
      data: { status: 'paused' },
    });

    return reply.send({ success: true, data: sub });
  });

  // ── POST /v1/user-subscriptions/:id/resume ───────────────────────────────
  server.post('/:id/resume', { preHandler: [authenticate] }, async (req: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const id = parseId(req.params.id, reply);
    if (!id) return;

    const existing = await server.prisma.userSubscription.findFirst({
      where: { id, userId: req.user.sub, deletedAt: null },
    });
    if (!existing) return reply.status(404).send({ error: 'NOT_FOUND', message: 'Subscription not found' });

    const sub = await server.prisma.userSubscription.update({
      where: { id },
      data: { status: 'active', cancelledAt: null },
    });

    // Re-create reminder
    const reminderId = await upsertLinkedReminder(server, req.user.sub, {
      id:                 sub.id,
      name:               sub.name,
      nextBillingDate:    sub.nextBillingDate,
      reminderDaysBefore: sub.reminderDaysBefore,
      reminderId:         sub.reminderId,
    });
    if (reminderId !== sub.reminderId) {
      await server.prisma.userSubscription.update({ where: { id }, data: { reminderId } });
    }

    return reply.send({ success: true, data: { ...sub, reminderId } });
  });

  // ── DELETE /v1/user-subscriptions/:id ────────────────────────────────────
  server.delete('/:id', { preHandler: [authenticate] }, async (req: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => {
    const id = parseId(req.params.id, reply);
    if (!id) return;

    const existing = await server.prisma.userSubscription.findFirst({
      where: { id, userId: req.user.sub, deletedAt: null },
    });
    if (!existing) return reply.status(404).send({ error: 'NOT_FOUND', message: 'Subscription not found' });

    await server.prisma.userSubscription.update({
      where: { id },
      data: { deletedAt: new Date() },
    });

    // Soft-delete linked reminder too
    if (existing.reminderId) {
      await server.prisma.reminder.updateMany({
        where: { id: existing.reminderId, status: 'pending' },
        data:  { status: 'deleted', deletedAt: new Date() },
      });
    }

    return reply.status(204).send();
  });
}
